# I will be adding more stuff soon, if you have any suggestions 
# open a suggestion ticket at http://dev.bukkit.org/server-mods/basiccontrol/tickets/
# and I will probably add it :)

# The Economy: area allows you to change settings for naming, enabling and changing the
# default amount of money(the money they get when their account is created)
# The messages: area allows you to change the messages displayed, you can use %p to display a players display-name, 
# %t to show the targets display-name (when you are giving a player money)
# %money is the amount of money, either the money being given or the money you have
# %name returns the name of the economy(defaults to dollars)
# You can also use colors by using & and the color-code

# For Administration %player is the kicked/banned player, and %kicker or %banner is the person who 
# used the command(if its console it replaces with "console")
Economy:
    enabled: true
    name: Dollars
    default amount: 1000
Messages:
    Economy:
        account-create-message: '&bYour balance has been set to &6%money &b%name'
        give-message: '&bYou gave %t &6%money &b%name'
        receive-message: '&b%p gave you &6%money &b%name'
        tell-message: '%p &bHas &6%money &b%name'
        check-message: '&bYou have &6%money &b%name'
        disabled-message: '&cThe economy is currently disabled, sorry!'
        not-enough-money: '&cYou dont have enough &b%name'
    Administration:
        kick-message: '&cYou have been kicked by %kicker'
        kick-broadcast: '%player &chas been kicked by %kicker'
        ban-message: '&cYou have been banned by %banner'
        ban-broadcast: '%player &chas been banned by %banner'
Other-Settings:
    show balance on join: true