# I will be adding more stuff soon, if you have any suggestions 
# open a suggestion ticket at http://dev.bukkit.org/server-mods/basiccontrol/tickets/
# and I will probably add it :)

# The Economy: area allows you to change settings for naming, enabling and changing the
# default amount of money(the money they get when their account is created)

# The messages: area allows you to change the messages displayed, you can use %p to display a players display-name, 
# %t to show the targets display-name (when you are giving a player money)
# %money is the amount of money, either the money being given or the money you have
# %name returns the name of the economy(defaults to dollars)
# You can also use colors by using & and the color-code
Economy:    
    enabled: true
    name: Dollars
    default amount: 1000
Messages:
    account-create-message: '&bYour balance has been set to &6%money &b%name'
    give-message: '&bYou gave %t %money %name'
    receive-message: '&b%p gave you %money %name'
    tell-message: '%p &bHas %money %name'
    check-message: '&bYou have &6%money &b%name'
    disabled-message: '&cThe economy is currently disabled, sorry!'
    not-enough-money: '&cYou dont have enough %name'
Other-Settings:
    show balance on join: true
    
version: 0.1